import React from "react";

    export const suppliesTornado = [
        {id: 0,
         supply: "Sturdy shoes and work gloves (for walking over debris)"},
        {id: 1,
         supply: "Helmet or hard hat (to protect against falling debris)"},
        {id: 2,
         supply: "Emergency cash (ATMs may be down)"},
        {id: 3,
         supply: "Blankets or sleeping bags (in case of prolonged power outage)"},
        {id: 4,
         supply:"Water (one gallon per person per day for several days, for drinking and sanitation)"},
        {id: 5,
         supply:"Food (at least a several-day supply of non-perishable food, rec to have a can opener handy)"},
        {id: 6,
         supply:"Battery-powered or hand crank radio and a NOAA Weather Radio with tone alert"},
        {id: 7,
         supply:"Flashlight"},
        {id: 8,
         supply:"First aid kit"},
        {id: 9,
         supply:"Extra batteries"},
        {id: 10,
         supply:"Whistle (to signal for help)"},
        {id: 11,
         supply:"Dust mask (to help filter contaminated air)"},
        {id: 12,
         supply:"Plastic sheeting, scissors and duct tape (to shelter in place)"},
        {id: 13,
         supply:"Moist towelettes, garbage bags and plastic ties (for personal sanitation)"},
        {id: 14,
         supply:"Wrench or pliers (to turn off utilities)"},
        {id: 15,
         supply:"Manual can opener (for food)"},
        {id: 16,
         supply:"Local maps"},
        {id: 17,
         supply:"Cell phone with chargers and a backup battery"},
    ]
     export const suppliesEartquake = [
        {id: 0,
         supply: "Goggles and heavy-duty gloves (to clear rubble safely)"},
        {id: 1,
         supply: "Crowbar or pry bar (for emergency exits)"},
        {id: 2,
         supply: "Sturdy shoes (broken glass and debris expected)"},
        {id: 3,
         supply: "Emergency contact card (in case cell service is out)"},
        {id: 4,
         supply:"Water (one gallon per person per day for several days, for drinking and sanitation)"},
        {id: 5,
         supply:"Food (at least a several-day supply of non-perishable food, rec to have a can opener handy)"},
        {id: 6,
         supply:"Battery-powered or hand crank radio and a NOAA Weather Radio with tone alert"},
        {id: 7,
         supply:"Flashlight"},
        {id: 8,
         supply:"First aid kit"},
        {id: 9,
         supply:"Extra batteries"},
        {id: 10,
         supply:"Whistle (to signal for help)"},
        {id: 11,
         supply:"Dust mask (to help filter contaminated air)"},
        {id: 12,
         supply:"Plastic sheeting, scissors and duct tape (to shelter in place)"},
        {id: 13,
         supply:"Moist towelettes, garbage bags and plastic ties (for personal sanitation)"},
        {id: 14,
         supply:"Wrench or pliers (to turn off utilities)"},
        {id: 15,
         supply:"Manual can opener (for food)"},
        {id: 16,
         supply:"Local maps"},
        {id: 17,
         supply:"Cell phone with chargers and a backup battery"},
    ]
     export const suppliesWildfire = [
        {id: 0,
         supply: "N95 masks (to protect against smoke inhalation)"},
        {id: 1,
         supply: "Fire-resistant blanket or clothing"},
        {id: 2,
         supply: "Spray bottles or towels (to cool skin if exposed to heat)"},
        {id: 3,
         supply: "Evacuation route map with alternate exits"},
        {id: 4,
         supply:"Water (one gallon per person per day for several days, for drinking and sanitation)"},
        {id: 5,
         supply:"Food (at least a several-day supply of non-perishable food, rec to have a can opener handy)"},
        {id: 6,
         supply:"Battery-powered or hand crank radio and a NOAA Weather Radio with tone alert"},
        {id: 7,
         supply:"Flashlight"},
        {id: 8,
         supply:"First aid kit"},
        {id: 9,
         supply:"Extra batteries"},
        {id: 10,
         supply:"Whistle (to signal for help)"},
        {id: 11,
         supply:"Dust mask (to help filter contaminated air)"},
        {id: 12,
         supply:"Plastic sheeting, scissors and duct tape (to shelter in place)"},
        {id: 13,
         supply:"Moist towelettes, garbage bags and plastic ties (for personal sanitation)"},
        {id: 14,
         supply:"Wrench or pliers (to turn off utilities)"},
        {id: 15,
         supply:"Manual can opener (for food)"},
        {id: 16,
         supply:"Local maps"},
        {id: 17,
         supply:"Cell phone with chargers and a backup battery"},
    ]