import React from "react";

    export const supplies = [
        {id: 0,
         supply:"Water (one gallon per person per day for several days, for drinking and sanitation)"},
        {id: 1,
         supply:"Food (at least a several-day supply of non-perishable food)"},
        {id: 2,
         supply:"Battery-powered or hand crank radio and a NOAA Weather Radio with tone alert"},
        {id: 3,
         supply:"Flashlight"},
        {id: 4,
         supply:"First aid kit"},
        {id: 5,
         supply:"Extra batteries"},
        {id: 6,
         supply:"Whistle (to signal for help)"},
        {id: 7,
         supply:"Dust mask (to help filter contaminated air)"},
        {id: 8,
         supply:"Plastic sheeting, scissors and duct tape (to shelter in place)"},
        {id: 9,
         supply:"Moist towelettes, garbage bags and plastic ties (for personal sanitation)"},
        {id: 10,
         supply:"Wrench or pliers (to turn off utilities)"},
        {id: 11,
         supply:"Manual can opener (for food)"},
        {id: 12,
         supply:"Local maps"},
        {id: 13,
         supply:"Cell phone with chargers and a backup battery"},
    ]
    